### ISSUE TITLE
Inquiry About Implementation of "Human-in-the-loop Guidance" in Your Research

### ISSUE THREAD

**Issue by pq-dong** [princeton-nlp/USACO#1]
Hi benshi34,

First of all, I'd like to commend you on the fantastic work presented in your research. I've thoroughly enjoyed reading your paper and exploring the accompanying code. The concepts you've explored are incredibly inspiring and have significant potential.

However, as I delved into the codebase, I noticed that the implementation of the "Human-in-the-loop Guidance" mentioned in the paper is not included. This aspect of your research is particularly intriguing to me, and I would love to understand more about it.

Could you please clarify how the "Human-in-the-loop Guidance" is technically realized? Additionally, do you have any plans to release this portion of the code as open source in the future?

Thank you very much for your time and assistance. I look forward to your response and appreciate all the effort you’ve put into this work.

Best regards

**Comment by benshi34** [comment]
See: https://benshi34.github.io/blog/2024/human-in-the-loop/ for sample trajectories!
